openapi: 3.0.0
info:
  title: Test A 3
  description: Test A description 3
  version: 1.0.0
  x-cortex-git:
    github:
      repository: voytekgar/test1
  x-cortex-tag: test-a
  x-cortex-link:
  - url: https://github.com/voytekgar/test1
    name: Github Repository
    type: documentation
  x-cortex-owners:
  - type: SLACK
    channel: engineering
  - type: email
    email: wojciech.garncarz@cortex.io
  - type: email
    email: zenon.garncarz@cortex.io
  - type: email
    email: zenon2.garncarz@cortex.io
  x-cortex-dependency:
  - tag: brain-app
